"""
system_modules/device_control/module.py — DeviceControlModule.

Universal smart-device manager. In-process system module — runs inside the
selena-core container, exposes a router at /api/ui/modules/device-control/.

Owns the ``device.on`` / ``device.off`` voice intents:
  voice.intent → resolve target device by entity_type + location → driver
  → set_state → publish device.state_changed → speak action ack via TTS.

For each registered device the module spawns one watcher coroutine that
holds a persistent connection to the device through the right driver and
yields state events as they're pushed by the device. No periodic polling.
"""
from __future__ import annotations

import asyncio
import json
import logging
import time
from pathlib import Path
from typing import Any

from fastapi import APIRouter
from sqlalchemy import select, update

from core.module_loader.system_module import SystemModule

from .drivers import DeviceDriver, DriverError, get_driver
from .providers import ProviderLoader

logger = logging.getLogger(__name__)

MODULE_DIR = Path(__file__).parent

# Voice intents this module owns. Strings match seed_intents_to_db.py.
INTENT_ON = "device.on"
INTENT_OFF = "device.off"
# Climate-specific intents (target air_conditioner / thermostat devices).
INTENT_SET_TEMPERATURE = "device.set_temperature"
INTENT_SET_MODE = "device.set_mode"
INTENT_SET_FAN_SPEED = "device.set_fan_speed"
# Read-only query intents (no driver write — return current state via TTS).
INTENT_QUERY_TEMPERATURE = "device.query_temperature"
# Lock-specific intents (target Matter / Z-Wave door locks).
INTENT_LOCK = "device.lock"
INTENT_UNLOCK = "device.unlock"
# Whole-house / whole-room power control. entity + location are
# optional filters — unset = match everything.
INTENT_ALL_OFF = "house.all_off"
INTENT_ALL_ON = "house.all_on"

#: All voice intents owned by this module — used by _claim_intent_ownership.
OWNED_INTENTS = [
    INTENT_ON,
    INTENT_OFF,
    INTENT_SET_TEMPERATURE,
    INTENT_SET_MODE,
    INTENT_SET_FAN_SPEED,
    INTENT_QUERY_TEMPERATURE,
    INTENT_LOCK,
    INTENT_UNLOCK,
    INTENT_ALL_OFF,
    INTENT_ALL_ON,
]

def _entity_filter_for(intent: str) -> tuple[str, ...] | None:
    """Read ``intent_definitions.entity_types`` from the IntentCompiler
    cache and return a tuple to feed into ``_resolve_device``.

    Empty list / missing row → no filter (``None``). Modules declare
    their supported entity types in ``_OWNED_INTENT_META``; core reads
    them via the compiled cache so this file has zero hardcoded
    entity-type lists.
    """
    try:
        from system_modules.llm_engine.intent_compiler import get_intent_compiler
        defn = get_intent_compiler().get_definition(intent)
        types = list(defn.entity_types) if defn and defn.entity_types else []
        return tuple(types) if types else None
    except Exception:
        return None


class DeviceControlModule(SystemModule):
    name = "device-control"

    def __init__(self) -> None:
        super().__init__()
        self._drivers: dict[str, DeviceDriver] = {}
        self._watch_tasks: dict[str, asyncio.Task] = {}
        self._stopping: bool = False
        self.provider_loader: ProviderLoader | None = None

    # ── Lifecycle ────────────────────────────────────────────────────────

    async def start(self) -> None:
        self._stopping = False
        # Initialise the provider loader: bootstrap built-in providers on
        # first start, then dynamically import every enabled driver class.
        # No eager imports — providers are discovered from the registry DB.
        try:
            self.provider_loader = ProviderLoader(self._session_factory)
            await self.provider_loader.bootstrap_builtins()
            loaded = await self.provider_loader.load_enabled()
            # Mirror into drivers.registry.DRIVERS so get_driver() sees them.
            from .drivers import registry as drv_registry
            drv_registry.DRIVERS.clear()
            drv_registry.DRIVERS.update(loaded)
        except Exception as exc:
            logger.exception(
                "device-control: provider loader failed: %s — continuing with no drivers",
                exc,
            )
        # Subscribe to voice intents (Tier 0/1 already match the regex
        # patterns generated by PatternGenerator from each device).
        self.subscribe(["voice.intent"], self._on_voice_intent)
        # Adopt the orphan intent definitions so the module catalogue knows
        # we own them. Idempotent.
        try:
            await self._claim_intent_ownership()
        except Exception as exc:
            logger.warning("device-control: claim ownership failed: %s", exc)
        # Spawn watchers for every device we manage.
        try:
            await self._spawn_watchers_for_existing_devices()
        except Exception as exc:
            logger.warning("device-control: failed to spawn initial watchers: %s", exc)
        logger.info("DeviceControlModule started")

    async def stop(self) -> None:
        self._stopping = True
        for did, task in list(self._watch_tasks.items()):
            task.cancel()
        for did, task in list(self._watch_tasks.items()):
            try:
                await task
            except (asyncio.CancelledError, Exception):
                pass
        self._watch_tasks.clear()
        for drv in list(self._drivers.values()):
            try:
                await drv.disconnect()
            except Exception:
                pass
        self._drivers.clear()
        self._cleanup_subscriptions()
        logger.info("DeviceControlModule stopped")

    # ── Router ───────────────────────────────────────────────────────────

    def get_router(self) -> APIRouter:
        from .routes import build_router  # local import to avoid circular
        router = build_router(self)
        self._register_html_routes(router, __file__)
        return router

    # ── Public helpers used by routes.py ─────────────────────────────────

    async def add_device_watcher(self, device_id: str) -> None:
        """Spawn a watcher for a newly added device. Called from POST /devices.

        Skips disabled devices — they are visible in the registry but not
        actively managed (no driver connection, no command dispatch).
        """
        if device_id in self._watch_tasks:
            return
        async with self._db_session() as session:
            from core.registry.models import Device
            d = await session.get(Device, device_id)
            if d is None or not bool(d.enabled):
                return
        task = asyncio.create_task(self._watch_device(device_id))
        self._watch_tasks[device_id] = task

    async def remove_device_watcher(self, device_id: str) -> None:
        task = self._watch_tasks.pop(device_id, None)
        if task is not None:
            task.cancel()
            try:
                await task
            except (asyncio.CancelledError, Exception):
                pass
        drv = self._drivers.pop(device_id, None)
        if drv is not None:
            try:
                await drv.disconnect()
            except Exception:
                pass

    async def execute_command(self, device_id: str, state: dict[str, Any]) -> None:
        """Apply a state update to a device through its driver. Used by
        the routes for /devices/{id}/command and /devices/{id}/test.

        Refuses to operate on disabled devices — those are intentionally
        offline (typically tuya_cloud entries where local control isn't
        available). The user must explicitly enable them first.
        """
        async with self._db_session() as session:
            from core.registry.models import Device
            d = await session.get(Device, device_id)
            if d is None:
                raise DriverError(f"Device {device_id} not found in registry")
            if not bool(d.enabled):
                raise DriverError(
                    "Device is disabled — local control unavailable. "
                    "Enable it via PATCH /devices/{id} {\"enabled\": true} "
                    "if you accept cloud-only control."
                )

        # First attempt against the (possibly cached) driver. On any
        # DriverError, drop the cached instance and try once more with a
        # fresh connection. This recovers from session-key desync without
        # waiting for the watcher's exponential backoff.
        drv: DeviceDriver | None = None
        try:
            drv = await self._get_or_create_driver(device_id)
            await drv.set_state(state)
        except DriverError:
            stale = self._drivers.pop(device_id, None)
            if stale is not None:
                try:
                    await stale.disconnect()
                except Exception:
                    pass
            drv = await self._get_or_create_driver(device_id)
            await drv.set_state(state)

        await self.patch_device_state(device_id, state)
        await self.publish("device.state_changed", {
            "device_id": device_id,
            "new_state": state,
            "source": self.name,
        })

    # ── Voice intent handler ─────────────────────────────────────────────

    async def _on_voice_intent(self, event: Any) -> None:
        try:
            payload = event.payload or {}
            intent = payload.get("intent", "")
            if intent not in OWNED_INTENTS:
                return
            params = payload.get("params") or {}

            # Composite-pattern resolver: if FastMatcher hit one of the
            # rebuild_composite_device_patterns() rows the regex captured a
            # name + optional location. Translate the name into a real
            # device_id via the in-memory index so _resolve_device picks
            # the matching row directly instead of guessing from filters.
            if (params.get("entity_ref") or "").strip() == "device:composite":
                name_en = (params.get("name") or "").strip().lower()
                if name_en:
                    try:
                        from system_modules.llm_engine.pattern_generator import (
                            get_pattern_generator,
                        )
                        gen = get_pattern_generator()
                    except Exception as exc:
                        logger.debug("composite resolve failed: %s", exc)
                        gen = None

                    if gen is not None:
                        device_id = gen.get_device_id_by_name(name_en)
                        if device_id:
                            # Unique name → fast path, jump straight to row.
                            params = {**params, "device_id": device_id}
                        elif gen.is_ambiguous_name(name_en):
                            # Ambiguous: 2+ devices share this name. We need
                            # _resolve_device's location-based disambiguation,
                            # but its tier 1/2 search the user-language
                            # device.location AND meta.name_en — so feed the
                            # captured name through as a synthetic ``entity``
                            # hint that the existing ilike filters will pick
                            # up. The location group from the composite
                            # regex is already in params["location"].
                            logger.info(
                                "composite: ambiguous name %r — disambiguating by location=%r",
                                name_en, params.get("location"),
                            )
                            params = {**params, "name_en": name_en}

            # Read-only query intents bypass the write pipeline below —
            # they don't translate to a driver state, just read the cached
            # value and speak it back.
            if intent == INTENT_QUERY_TEMPERATURE:
                await self._handle_query_temperature(params)
                return

            # Whole-house / whole-room mass power control. Enumerates
            # ALL registered devices (optionally filtered by entity +
            # location) and fans an on/off command out. Bypasses the
            # single-device resolver entirely.
            if intent in (INTENT_ALL_OFF, INTENT_ALL_ON):
                await self._handle_all_power(intent, params)
                return

            # Build the target logical state for this intent. Climate intents
            # need parameter parsing; on/off are trivial.
            try:
                target_state = self._intent_to_state(intent, params)
            except ValueError as exc:
                logger.info("device-control: bad params for %s: %s", intent, exc)
                return
            if target_state is None:
                return

            # Ambiguous without location: IntentRouter matched N devices
            # of this entity_type but the user didn't say a room. Refuse
            # to act, ask for the room via TTS.
            if params.get("ambiguous"):
                await self.speak_action(intent, {
                    "result": "needs_location",
                    "entity": params.get("entity"),
                    "count": len(params.get("candidates") or []),
                })
                return

            # Group-action branch: IntentRouter pre-resolved N devices
            # of this type in this room. Fan the command out — typical
            # case is "turn off the lights in the bedroom" where there
            # are 2-3 lights.
            device_ids = params.get("device_ids") or []
            if device_ids:
                await self._apply_group(
                    intent, target_state, params, device_ids,
                )
                return

            entity_filter = _entity_filter_for(intent)
            device = await self._resolve_device(params, entity_filter=entity_filter)
            if device is None:
                logger.info(
                    "device-control: no device matches intent=%s params=%s",
                    intent, params,
                )
                await self.speak_action(intent, {
                    "result": "not_found",
                    "entity": params.get("entity"),
                    "location": params.get("location"),
                })
                return

            # Enrich base state with capability-matched params (color,
            # brightness, colour_temp) — only keys the device actually
            # supports in its current state are merged.
            target_state = self._enrich_state_from_params(
                target_state, params, device,
            )

            try:
                drv = await self._get_or_create_driver(device["device_id"])
                await drv.set_state(target_state)
            except DriverError as exc:
                logger.warning(
                    "device-control: driver error for %s: %s",
                    device["device_id"], exc,
                )
                _emeta = device.get("meta") or {}
                if isinstance(_emeta, str):
                    import json as _json
                    try: _emeta = _json.loads(_emeta)
                    except Exception: _emeta = {}
                await self.speak_action(intent, {
                    "result": "driver_error",
                    "device_name": _emeta.get("name_en") or device["name"],
                    "error": str(exc),
                })
                return

            # Optimistically merge target into stored state.
            current = device.get("state") or {}
            current.update(target_state)
            await self.patch_device_state(device["device_id"], current)
            await self.publish("device.state_changed", {
                "device_id": device["device_id"],
                "new_state": current,
                "source": self.name,
            })

            _meta = device.get("meta") or {}
            if isinstance(_meta, str):
                import json as _json
                try: _meta = _json.loads(_meta)
                except Exception: _meta = {}
            # Pass BOTH the user-said bits (entity / name_en / location
            # from params) and the resolved device's registry fields.
            # action_phrasing._device_label picks the word the user
            # literally said — "світло" / "light" wins over a custom
            # Кабінет → "office" nickname.
            ack: dict[str, Any] = {
                "result": "ok",
                "entity": params.get("entity") or device.get("entity_type"),
                "name_en": params.get("name_en"),
                "device_name": _meta.get("name_en") or device["name"],
                "location": (
                    params.get("location")
                    or _meta.get("location_en")
                    or device.get("location")
                ),
            }
            if intent in (INTENT_ON, INTENT_OFF):
                ack["state"] = "on" if intent == INTENT_ON else "off"
            elif intent in (INTENT_LOCK, INTENT_UNLOCK):
                ack["state"] = "locked" if intent == INTENT_LOCK else "unlocked"
            elif intent == INTENT_SET_TEMPERATURE:
                ack["temperature"] = target_state.get("target_temp")
            elif intent == INTENT_SET_MODE:
                ack["mode"] = target_state.get("mode")
            elif intent == INTENT_SET_FAN_SPEED:
                ack["fan_speed"] = target_state.get("fan_speed")
            await self.speak_action(intent, ack)
        except Exception as exc:
            logger.exception("device-control: voice intent handler crashed: %s", exc)

    # ── Group action ────────────────────────────────────────────────────

    async def _apply_group(
        self,
        intent: str,
        target_state: dict,
        params: dict,
        device_ids: list[str],
    ) -> None:
        """Apply the same target_state to every device in ``device_ids``.

        Driver errors on individual devices are logged and counted but
        don't abort the group — partial success is fine. State is merged
        and published per-device via the same path as the single-device
        handler, so downstream listeners see N ``device.state_changed``
        events as if the user had fired N individual commands.
        """
        from core.registry.models import Device

        applied = 0
        failed = 0
        async with self._db_session() as session:
            rows = [await session.get(Device, did) for did in device_ids]
        rows = [r for r in rows if r is not None and bool(r.enabled)]

        for row in rows:
            device = {
                "device_id": row.device_id,
                "name": row.name,
                "entity_type": row.entity_type,
                "location": row.location,
                "protocol": row.protocol,
                "state": json.loads(row.state) if row.state else {},
                "meta": json.loads(row.meta) if row.meta else {},
            }
            # Per-device enrichment — color/brightness keys only apply
            # to devices whose current state supports them.
            per_state = self._enrich_state_from_params(
                dict(target_state), params, device,
            )
            try:
                drv = await self._get_or_create_driver(device["device_id"])
                await drv.set_state(per_state)
            except DriverError as exc:
                logger.warning(
                    "device-control: group driver error for %s: %s",
                    device["device_id"], exc,
                )
                failed += 1
                continue

            current = device.get("state") or {}
            current.update(per_state)
            await self.patch_device_state(device["device_id"], current)
            await self.publish("device.state_changed", {
                "device_id": device["device_id"],
                "new_state": current,
                "source": self.name,
            })
            applied += 1

        ack: dict[str, Any] = {
            "result": "group_ok" if applied else "group_error",
            "entity": params.get("entity"),
            "location": params.get("location"),
            "count": applied,
            "failed": failed,
        }
        if intent in (INTENT_ON, INTENT_OFF):
            ack["state"] = "on" if intent == INTENT_ON else "off"
        elif intent in (INTENT_LOCK, INTENT_UNLOCK):
            ack["state"] = "locked" if intent == INTENT_LOCK else "unlocked"
        elif intent == INTENT_SET_TEMPERATURE:
            ack["temperature"] = target_state.get("target_temp")
        elif intent == INTENT_SET_MODE:
            ack["mode"] = target_state.get("mode")
        elif intent == INTENT_SET_FAN_SPEED:
            ack["fan_speed"] = target_state.get("fan_speed")
        await self.speak_action(intent, ack)

    # ── Whole-house power ───────────────────────────────────────────────

    async def _handle_all_power(self, intent: str, params: dict) -> None:
        """Mass on/off across every registered device.

        Optional filters in ``params``:
          - ``entity``    — restrict to entity_type (e.g. only lights)
          - ``location``  — restrict to a room (bilingual fuzzy match)

        No filters → act on every device under device-control. Climate
        devices are EXCLUDED when turning everything on to avoid
        unintended heating/cooling — use an explicit climate intent
        instead. All-off has no such exclusion: a blanket "off" is safe.
        """
        from core.registry.service import DeviceRegistry

        entity = (params.get("entity") or "").strip().lower() or None
        location = (params.get("location") or "").strip() or None

        async with self._db_session() as session:
            registry = DeviceRegistry(session)
            # entity_type filter: exact match. If user said a general
            # "все"/"everything" with no entity, fetch the full inventory.
            if entity:
                devices = await registry.query(
                    entity_type=entity, location=location,
                )
            else:
                devices = await registry.query(location=location)

        # Restrict to rows we own.
        devices = [d for d in devices if d.module_id == self.name and bool(d.enabled)]

        # For all_on without an entity filter, exclude climate devices
        # (ac / thermostat / radiator) — "turn on everything" at 2am
        # shouldn't spin up the heater. User must be explicit for climate.
        if intent == INTENT_ALL_ON and not entity:
            devices = [
                d for d in devices
                if (d.entity_type or "").lower() not in
                   ("air_conditioner", "thermostat", "radiator")
            ]

        if not devices:
            await self.speak_action(intent, {
                "result": "not_found",
                "entity": entity, "location": location, "count": 0,
            })
            return

        target_state = {"on": intent == INTENT_ALL_ON}
        applied = 0
        failed = 0
        for row in devices:
            try:
                drv = await self._get_or_create_driver(row.device_id)
                await drv.set_state(target_state)
            except DriverError as exc:
                logger.warning(
                    "device-control: all_power driver error for %s: %s",
                    row.device_id, exc,
                )
                failed += 1
                continue
            current = (json.loads(row.state) if row.state else {}) or {}
            current.update(target_state)
            await self.patch_device_state(row.device_id, current)
            await self.publish("device.state_changed", {
                "device_id": row.device_id,
                "new_state": current,
                "source": self.name,
            })
            applied += 1

        await self.speak_action(intent, {
            "result": "group_ok" if applied else "group_error",
            "state": "on" if intent == INTENT_ALL_ON else "off",
            "entity": entity, "location": location,
            "count": applied, "failed": failed,
        })

    # ── Read-only query handlers ─────────────────────────────────────────

    async def _handle_query_temperature(self, params: dict) -> None:
        """Read current_temp from the matching climate device and speak it.

        Targets air_conditioner / thermostat devices in the requested
        location. The actual sentence ("It's 22 degrees in the living
        room") is generated by VoiceCore's rephrase LLM from the action
        context dict — see speak_action.
        """
        entity_filter = _entity_filter_for(INTENT_QUERY_TEMPERATURE)
        device = await self._resolve_device(params, entity_filter=entity_filter)
        if device is None:
            await self.speak_action(INTENT_QUERY_TEMPERATURE, {
                "result": "not_found",
                "location": params.get("location"),
            })
            return

        state = device.get("state") or {}
        # gree driver writes "current_temp"; thermostat / Matter drivers
        # may use "current_temperature" — accept both.
        current = state.get("current_temp")
        if current is None:
            current = state.get("current_temperature")
        if current is None:
            _qm = device.get("meta") or {}
            if isinstance(_qm, str):
                import json as _json
                try: _qm = _json.loads(_qm)
                except Exception: _qm = {}
            await self.speak_action(INTENT_QUERY_TEMPERATURE, {
                "result": "no_data",
                "device_name": _qm.get("name_en") or device["name"],
                "location": _qm.get("location_en") or device.get("location"),
            })
            return

        _qm = device.get("meta") or {}
        if isinstance(_qm, str):
            import json as _json
            try: _qm = _json.loads(_qm)
            except Exception: _qm = {}
        await self.speak_action(INTENT_QUERY_TEMPERATURE, {
            "result": "ok",
            "temperature": current,
            "device_name": _qm.get("name_en") or device["name"],
            "location": _qm.get("location_en") or device.get("location"),
        })

    # ── Intent → state translation ───────────────────────────────────────

    @staticmethod
    def _intent_to_state(intent: str, params: dict) -> dict[str, Any] | None:
        """Convert ``(intent, params)`` from the voice layer into a logical
        state dict ready for ``driver.set_state()``.

        Returns ``None`` if the intent is not understood (caller bails out
        silently). Raises ``ValueError`` if the intent IS understood but its
        params are missing/invalid (caller logs and bails).
        """
        if intent == INTENT_ON:
            return {"on": True}
        if intent == INTENT_OFF:
            return {"on": False}

        if intent == INTENT_LOCK:
            return {"locked": True}
        if intent == INTENT_UNLOCK:
            return {"locked": False}

        if intent == INTENT_SET_TEMPERATURE:
            raw = params.get("level") or params.get("temperature")
            if raw is None:
                raise ValueError("missing 'level' parameter")
            try:
                level = int(raw)
            except (TypeError, ValueError) as exc:
                raise ValueError(f"non-integer level: {raw!r}") from exc
            return {"target_temp": level}

        if intent == INTENT_SET_MODE:
            raw = (params.get("mode") or params.get("value") or "").strip().lower()
            if not raw:
                raise ValueError("missing 'mode' parameter")
            # No core-side allowlist — the driver decides what it
            # supports. Unknown modes bubble up as DriverError and the
            # user hears a driver_error speech template.
            return {"mode": raw}

        if intent == INTENT_SET_FAN_SPEED:
            raw = (
                params.get("level")
                or params.get("speed")
                or params.get("value")
                or ""
            ).strip().lower()
            if not raw:
                raise ValueError("missing fan speed")
            return {"fan_speed": raw}

        return None

    @staticmethod
    def _enrich_state_from_params(
        base_state: dict, params: dict, device: dict,
    ) -> dict[str, Any]:
        """Enrich state dict with capability-matched params.

        If the voice command included color / brightness / color_temp AND
        the resolved device supports them (indicated by keys already
        present in its ``state``), merge them into the outgoing state.
        Capabilities that the device doesn't have are silently ignored,
        so the same voice params work across heterogeneous devices.
        """
        state = dict(base_state)
        device_state = device.get("state") or {}

        # Brightness: percentage (0-100 from extract_params) → 0-254
        if "brightness" in params and "brightness" in device_state:
            try:
                pct = float(params["brightness"])
                state["brightness"] = min(254, max(0, int(pct * 254 / 100)))
            except (TypeError, ValueError):
                pass

        # Color: name → hue + saturation (only if device has hue key)
        if "color" in params and "hue" in device_state:
            from system_modules.llm_engine.embedding_classifier import COLOR_TO_HS
            hs = COLOR_TO_HS.get(params["color"])
            if hs:
                state["hue"] = hs[0]
                state["saturation"] = hs[1]

        # Color temperature: kelvin value from extract_params
        if "color_temp" in params and "colour_temp" in device_state:
            try:
                state["colour_temp"] = int(params["color_temp"])
            except (TypeError, ValueError):
                pass

        return state

    # ── Device resolution ────────────────────────────────────────────────

    async def _resolve_device(
        self,
        params: dict,
        entity_filter: tuple[str, ...] | None = None,
    ) -> dict | None:
        """Find ONE device matching params (entity, location, name).

        ``entity_filter`` narrows the candidate set to devices whose
        ``entity_type`` is in the given tuple — used by climate intents so
        a "set temperature" command cannot accidentally match a light or
        switch in the same room.

        Strategy (stops at the first tier that returns exactly one match):
          1. Strict: entity_type AND location both match.
          2. Location-only: only ``location`` supplied or entity missed.
             Matches device.location OR device.name OR meta.name_en —
             the user may say the ROOM, the DISPLAY NAME, or the ENGLISH
             name interchangeably ("turn on the cabinet light" → both
             name and location can be the same word).
          3. Entity-only: only ``entity`` supplied.
          4. Fallback: single-device installation — return it if there's
             exactly one device under our management.

        Returns the device as a dict, or None if zero/many matches.
        """
        from core.registry.models import Device
        from sqlalchemy import or_

        entity = (params.get("entity") or "").lower().strip() or None
        location = (params.get("location") or "").lower().strip() or None
        explicit_id = (params.get("device_id") or "").strip() or None
        # Composite resolver hands us a name_en captured by the regex
        # when the same name is shared by 2+ devices. We use it as a
        # tier-0 disambiguation key against meta.name_en + location.
        explicit_name_en = (params.get("name_en") or "").strip().lower() or None

        def _row_to_dict(d) -> dict:
            return {
                "device_id": d.device_id,
                "name": d.name,
                "entity_type": d.entity_type,
                "location": d.location,
                "protocol": d.protocol,
                "state": json.loads(d.state) if d.state else {},
                "meta": json.loads(d.meta) if d.meta else {},
            }

        async with self._db_session() as session:
            # Fast path: composite resolver (or any caller) handed us a
            # concrete device_id — load it directly and skip the search
            # tiers. We still respect entity_filter as a sanity check so
            # an AC-only intent can never act on a light row by mistake.
            if explicit_id:
                d = await session.get(Device, explicit_id)
                if (
                    d is not None
                    and d.module_id == self.name
                    and bool(d.enabled)
                    and (
                        not entity_filter
                        or (d.entity_type or "").lower() in entity_filter
                    )
                ):
                    return _row_to_dict(d)
                return None

            base = select(Device).where(
                Device.module_id == self.name,
                Device.enabled == True,  # noqa: E712
            )
            if entity_filter:
                base = base.where(Device.entity_type.in_(entity_filter))

            # Tier 0: composite resolver passed an English name + a
            # location. Match meta.name_en exactly (substring) AND any
            # location field. This is the disambiguation path for
            # collisions like name_en="light" appearing in two rooms.
            if explicit_name_en and location:
                stmt = base.where(
                    Device.meta.ilike(f'%"name_en": "{explicit_name_en}"%'),
                    or_(
                        Device.location.ilike(f"%{location}%"),
                        Device.meta.ilike(f'%"location_en": "%{location}%'),
                    ),
                )
                rows = list((await session.execute(stmt)).scalars())
                if len(rows) == 1:
                    return _row_to_dict(rows[0])
                # If still ambiguous (or zero) the user gave us a room
                # the device isn't in — bail out so the caller speaks
                # "not found" instead of acting on the wrong device.
                return None

            # Tier 1: both entity_type AND location. Strict type filter
            # (ilike on entity_type) + location match against the
            # location column and meta.location_en — deliberately NOT
            # searching the name column: a device named "Kitchen Light"
            # must not hit when the user says location="kitchen" from a
            # different room.
            if entity and location:
                stmt = base.where(
                    Device.entity_type.ilike(f"%{entity}%"),
                    or_(
                        Device.location.ilike(f"%{location}%"),
                        Device.meta.ilike(f'%"location_en": "%{location}%'),
                    ),
                )
                rows = list((await session.execute(stmt)).scalars())
                if len(rows) == 1:
                    return _row_to_dict(rows[0])

            # Location-only tier (previously matched location against
            # name/meta.name_en) is intentionally removed — that "name
            # leak" let "kitchen" hit devices named "Kitchen Light" in
            # other rooms, producing silent room switches. Primary group
            # resolution has already happened in IntentRouter via
            # DeviceRegistry.query(entity_type, location).
            #
            # If a location was given but tier 1 didn't find a unique
            # match, don't fall through to entity-only or single-device
            # fallback — that would silently act in a different room.
            if location:
                return None

            # Tier 3: entity-type alone.
            if entity:
                stmt = base.where(Device.entity_type.ilike(f"%{entity}%"))
                rows = list((await session.execute(stmt)).scalars())
                if len(rows) == 1:
                    return _row_to_dict(rows[0])

            # Tier 4: single-device install — unambiguous fallback.
            rows = list((await session.execute(base)).scalars())
            if len(rows) == 1:
                return _row_to_dict(rows[0])

        return None

    # ── Watcher loop ─────────────────────────────────────────────────────

    async def _spawn_watchers_for_existing_devices(self) -> None:
        async with self._db_session() as session:
            from core.registry.models import Device
            result = await session.execute(
                select(Device.device_id).where(
                    Device.module_id == self.name,
                    Device.enabled == True,  # noqa: E712
                )
            )
            ids = [r[0] for r in result.all()]
        for did in ids:
            await self.add_device_watcher(did)

    async def _get_or_create_driver(self, device_id: str) -> DeviceDriver:
        if device_id in self._drivers:
            return self._drivers[device_id]
        async with self._db_session() as session:
            from core.registry.models import Device
            d = await session.get(Device, device_id)
            if d is None:
                raise DriverError(f"Device {device_id} not found in registry")
            protocol = d.protocol
            meta = json.loads(d.meta) if d.meta else {}
        drv = get_driver(device_id, protocol, meta)
        # Inject the EventBus publisher so drivers like MqttBridgeDriver can
        # forward commands to protocol_bridge via ``device.command`` events.
        drv.event_publisher = self.publish
        self._drivers[device_id] = drv
        return drv

    async def _watch_device(self, device_id: str) -> None:
        """Persistent push watcher with exponential reconnect backoff."""
        attempt = 0
        was_online: bool | None = None
        while not self._stopping:
            try:
                drv = await self._get_or_create_driver(device_id)
                state = await drv.connect()
                attempt = 0
                # Some drivers (e.g. Gree) learn a per-device key during
                # connect() and mutate self.meta in place. Persist that
                # back to the DB so the next reconnect skips the binding
                # handshake.
                await self._persist_driver_meta(device_id, drv)
                if state:
                    await self._apply_external_state(device_id, state)
                await self._publish_metering(device_id, drv)
                if was_online is not True:
                    await self._publish_online(device_id, True)
                    was_online = True

                async for new_state in drv.stream_events():
                    if self._stopping:
                        break
                    if new_state:
                        await self._apply_external_state(device_id, new_state)
                    await self._publish_metering(device_id, drv)
            except asyncio.CancelledError:
                raise
            except DriverError as exc:
                logger.info(
                    "device-control: %s offline (%s) — backing off",
                    device_id, exc,
                )
                if was_online is not False:
                    await self._publish_online(device_id, False)
                    was_online = False
                # Drop the broken driver instance so reconnect builds a fresh one.
                self._drivers.pop(device_id, None)
                attempt += 1

                # No automatic downgrade to cloud — local control is the
                # whole point. The device just stays "offline" until LAN
                # comes back. The user can manually flip enabled=true on a
                # cloud-only device if they accept the internet dependency.
                delay = min(60, 2 ** min(attempt, 6))
                try:
                    await asyncio.sleep(delay)
                except asyncio.CancelledError:
                    raise
            except Exception as exc:
                logger.exception(
                    "device-control: unexpected error in watcher %s: %s",
                    device_id, exc,
                )
                self._drivers.pop(device_id, None)
                try:
                    await asyncio.sleep(15)
                except asyncio.CancelledError:
                    raise

    async def _apply_external_state(self, device_id: str, state: dict) -> None:
        """Persist a state update from the device and broadcast on EventBus."""
        try:
            await self.patch_device_state(device_id, state)
        except Exception:
            pass
        await self.publish("device.state_changed", {
            "device_id": device_id,
            "new_state": state,
            "source": self.name,
        })

    async def _publish_online(self, device_id: str, online: bool) -> None:
        await self.publish(
            "device.online" if online else "device.offline",
            {"device_id": device_id},
        )

    async def _persist_driver_meta(self, device_id: str, drv: Any) -> None:
        """Write back any in-place mutations the driver made to its meta dict.

        Drivers that learn credentials during ``connect()`` (e.g. Gree's
        per-device AES key) update ``drv.meta`` directly. This helper
        diff-checks against the persisted JSON and only writes when the
        contents actually changed, so we don't pound the DB with no-op
        UPDATEs on every reconnect.
        """
        new_meta = getattr(drv, "meta", None)
        if not isinstance(new_meta, dict):
            return
        try:
            new_json = json.dumps(new_meta, sort_keys=True)
        except (TypeError, ValueError):
            return
        try:
            from core.registry.models import Device
            async with self._db_session() as session:
                async with session.begin():
                    d = await session.get(Device, device_id)
                    if d is None:
                        return
                    current_json = json.dumps(
                        json.loads(d.meta) if d.meta else {},
                        sort_keys=True,
                    )
                    if current_json == new_json:
                        return
                    d.set_meta(new_meta)
        except Exception as exc:
            logger.warning(
                "device-control: failed to persist meta for %s: %s",
                device_id, exc,
            )

    async def _publish_metering(self, device_id: str, drv: Any) -> None:
        """Drain any pending power-meter snapshot from the driver and emit
        ``device.power_reading`` on the bus. No-op for drivers that don't
        implement metering."""
        try:
            metering = drv.consume_metering()
        except Exception:
            return
        if not metering or "watts" not in metering:
            return
        await self.publish("device.power_reading", {
            "device_id": device_id,
            "watts": metering["watts"],
            "volts": metering.get("volts"),
            "amps": metering.get("amps"),
            "ts": time.time(),
            "source": self.name,
        })

    # ── Intent ownership claim ────────────────────────────────────────────

    #: Defaults used when an OWNED_INTENT has no row yet in
    #: ``intent_definitions``. Each module is the source of truth for its
    #: own "hard" intents (per the system architecture: modules declare
    #: what they can do; seed scripts are NOT used). Patterns are NOT
    #: seeded here on purpose — the LLM tier classifies everything from
    #: the dynamic intent catalog, and PatternGenerator can later add
    #: per-device regex shortcuts when devices register.
    _OWNED_INTENT_META: dict[str, dict] = {
        INTENT_ON: dict(
            noun_class="DEVICE", verb="on", priority=100,
            description=(
                "Turn a device on. Applies to any controllable device: "
                "light, lamp, bulb, switch, outlet, plug, socket, fan, "
                "air conditioner, AC, humidifier, heater, radiator, "
                "kettle, teapot, speaker, media player, TV, curtain, "
                "blind, shade, vacuum, robot vacuum. Also: start, run, "
                "launch, activate, open curtains, raise blinds, boil "
                "kettle, bright, brighter, dim, darker, make, "
                "brightness, color, change, put, maximum, minimum."
            ),
            entity_types=None,  # any type — core decides nothing
        ),
        INTENT_OFF: dict(
            noun_class="DEVICE", verb="off", priority=100,
            description=(
                "Turn a device off. Applies to any controllable device: "
                "light, lamp, bulb, switch, outlet, plug, socket, fan, "
                "air conditioner, AC, humidifier, heater, radiator, "
                "kettle, speaker, media player, TV, curtain, blind, "
                "shade, vacuum, robot vacuum. Also: stop, kill, put out, "
                "extinguish, close curtains, lower blinds, shut, "
                "deactivate, pause vacuum."
            ),
            entity_types=None,
        ),
        INTENT_SET_TEMPERATURE: dict(
            noun_class="CLIMATE", verb="set", priority=100,
            description="Set the target temperature on an air conditioner or thermostat",
            entity_types=["air_conditioner", "thermostat", "radiator"],
        ),
        INTENT_SET_MODE: dict(
            noun_class="CLIMATE", verb="set", priority=100,
            description=(
                "Set the operating mode (cool/heat/dry/fan/auto) of an "
                "air conditioner. Also: switch to heating, cooling, "
                "draining, heaters."
            ),
            entity_types=["air_conditioner", "thermostat"],
        ),
        INTENT_SET_FAN_SPEED: dict(
            noun_class="CLIMATE", verb="set", priority=100,
            description="Set the fan speed of an air conditioner or fan",
            entity_types=["air_conditioner", "fan"],
        ),
        INTENT_QUERY_TEMPERATURE: dict(
            noun_class="CLIMATE", verb="query", priority=100,
            description=(
                "Read the CURRENT temperature reported by an indoor "
                "climate device (air conditioner / thermostat) in a "
                "specific room. Returns the live sensor value, NOT the "
                "outdoor weather forecast."
            ),
            entity_types=["air_conditioner", "thermostat"],
        ),
        INTENT_LOCK: dict(
            noun_class="DEVICE", verb="lock", priority=100,
            description=(
                "Lock a smart lock — secure a door, prevent entry. "
                "Use for 'lock', 'close lock', 'secure'."
            ),
            entity_types=["lock", "door_lock"],
        ),
        INTENT_UNLOCK: dict(
            noun_class="DEVICE", verb="unlock", priority=100,
            description=(
                "Unlock a smart lock — release the lock, allow entry. "
                "Opposite of device.lock. Use for 'unlock', 'open lock', "
                "'open the door'."
            ),
            entity_types=["lock", "door_lock"],
        ),
        INTENT_ALL_OFF: dict(
            noun_class="HOUSE", verb="off", priority=100,
            description=(
                "Whole-house mass off — user said 'all' / 'everything'. "
                "NOT for single-device off (use device.off). Only fires "
                "when the query contains 'all', 'everything', 'все', "
                "'всі', 'всё'."
            ),
            entity_types=None,
        ),
        INTENT_ALL_ON: dict(
            noun_class="HOUSE", verb="on", priority=100,
            description=(
                "Whole-house mass on — user said 'all' / 'everything' "
                "together with an on verb. Only fires when the query "
                "contains 'all' / 'everything' / 'все'."
            ),
            entity_types=None,
        ),
    }

    async def _claim_intent_ownership(self) -> None:
        """Ensure every OWNED_INTENT exists in the DB and is owned by us.

        Creates missing definitions on the fly using ``_OWNED_INTENT_META``.
        This makes the module self-sufficient: it does not rely on
        ``scripts/seed_intents_to_db.py`` to populate ``intent_definitions``
        rows. Existing rows have their ``module`` column rewritten to
        ``device-control`` so any duplicates from older code paths land
        under our ownership.
        """
        if self._session_factory is None:
            return
        from core.registry.models import IntentDefinition
        import json as _json

        async with self._session_factory() as session:
            # Existing rows → claim ownership.
            await session.execute(
                update(IntentDefinition)
                .where(IntentDefinition.intent.in_(OWNED_INTENTS))
                .values(module=self.name)
            )

            # Sync entity_types on existing rows every boot so the DB
            # always reflects the module's current declared support list.
            # This is how new device types become valid for an intent —
            # the module updates its META and a restart rewrites the DB.
            for intent_name, meta in self._OWNED_INTENT_META.items():
                ent = meta.get("entity_types")
                payload = _json.dumps(list(ent)) if ent else None
                await session.execute(
                    update(IntentDefinition)
                    .where(IntentDefinition.intent == intent_name)
                    .values(
                        entity_types=payload,
                        description=meta["description"],
                    )
                )

            # Missing rows → insert with module-defined defaults.
            existing = {
                row[0] for row in (await session.execute(
                    select(IntentDefinition.intent).where(
                        IntentDefinition.intent.in_(OWNED_INTENTS)
                    )
                )).all()
            }
            for intent_name in OWNED_INTENTS:
                if intent_name in existing:
                    continue
                meta = self._OWNED_INTENT_META.get(intent_name)
                if meta is None:
                    continue
                ent = meta.get("entity_types")
                session.add(IntentDefinition(
                    intent=intent_name,
                    module=self.name,
                    noun_class=meta["noun_class"],
                    verb=meta["verb"],
                    priority=meta["priority"],
                    description=meta["description"],
                    source="module",
                    entity_types=_json.dumps(list(ent)) if ent else None,
                ))
            await session.commit()
