"""
system_modules/device_control/module.py — DeviceControlModule.

Universal smart-device manager. In-process system module — runs inside the
selena-core container, exposes a router at /api/ui/modules/device-control/.

Owns the ``device.on`` / ``device.off`` voice intents:
  voice.intent → resolve target device by entity_type + location → driver
  → set_state → publish device.state_changed → speak action ack via TTS.

For each registered device the module spawns one watcher coroutine that
holds a persistent connection to the device through the right driver and
yields state events as they're pushed by the device. No periodic polling.
"""
from __future__ import annotations

import asyncio
import json
import logging
import time
from pathlib import Path
from typing import Any

from fastapi import APIRouter
from sqlalchemy import select, update

from core.module_loader.system_module import SystemModule

from .drivers import DeviceDriver, DriverError, get_driver

logger = logging.getLogger(__name__)

MODULE_DIR = Path(__file__).parent

# Voice intents this module owns. Strings match seed_intents_to_db.py.
INTENT_ON = "device.on"
INTENT_OFF = "device.off"
# Climate-specific intents (target air_conditioner / thermostat devices).
INTENT_SET_TEMPERATURE = "device.set_temperature"
INTENT_SET_MODE = "device.set_mode"
INTENT_SET_FAN_SPEED = "device.set_fan_speed"

#: All voice intents owned by this module — used by _claim_intent_ownership.
OWNED_INTENTS = [
    INTENT_ON,
    INTENT_OFF,
    INTENT_SET_TEMPERATURE,
    INTENT_SET_MODE,
    INTENT_SET_FAN_SPEED,
]

#: Intent → entity_type filter. Voice resolution narrows to these devices so
#: a "set temperature" command cannot accidentally hit a light.
INTENT_ENTITY_FILTER: dict[str, tuple[str, ...]] = {
    INTENT_SET_TEMPERATURE: ("air_conditioner", "thermostat"),
    INTENT_SET_MODE: ("air_conditioner", "thermostat"),
    INTENT_SET_FAN_SPEED: ("air_conditioner", "fan"),
}


class DeviceControlModule(SystemModule):
    name = "device-control"

    def __init__(self) -> None:
        super().__init__()
        self._drivers: dict[str, DeviceDriver] = {}
        self._watch_tasks: dict[str, asyncio.Task] = {}
        self._stopping: bool = False

    # ── Lifecycle ────────────────────────────────────────────────────────

    async def start(self) -> None:
        self._stopping = False
        # Subscribe to voice intents (Tier 0/1 already match the regex
        # patterns generated by PatternGenerator from each device).
        self.subscribe(["voice.intent"], self._on_voice_intent)
        # Adopt the orphan intent definitions so the module catalogue knows
        # we own them. Idempotent.
        try:
            await self._claim_intent_ownership()
        except Exception as exc:
            logger.warning("device-control: claim ownership failed: %s", exc)
        # Spawn watchers for every device we manage.
        try:
            await self._spawn_watchers_for_existing_devices()
        except Exception as exc:
            logger.warning("device-control: failed to spawn initial watchers: %s", exc)
        logger.info("DeviceControlModule started")

    async def stop(self) -> None:
        self._stopping = True
        for did, task in list(self._watch_tasks.items()):
            task.cancel()
        for did, task in list(self._watch_tasks.items()):
            try:
                await task
            except (asyncio.CancelledError, Exception):
                pass
        self._watch_tasks.clear()
        for drv in list(self._drivers.values()):
            try:
                await drv.disconnect()
            except Exception:
                pass
        self._drivers.clear()
        self._cleanup_subscriptions()
        logger.info("DeviceControlModule stopped")

    # ── Router ───────────────────────────────────────────────────────────

    def get_router(self) -> APIRouter:
        from .routes import build_router  # local import to avoid circular
        router = build_router(self)
        self._register_html_routes(router, __file__)
        return router

    # ── Public helpers used by routes.py ─────────────────────────────────

    async def add_device_watcher(self, device_id: str) -> None:
        """Spawn a watcher for a newly added device. Called from POST /devices.

        Skips disabled devices — they are visible in the registry but not
        actively managed (no driver connection, no command dispatch).
        """
        if device_id in self._watch_tasks:
            return
        async with self._db_session() as session:
            from core.registry.models import Device
            d = await session.get(Device, device_id)
            if d is None or not bool(d.enabled):
                return
        task = asyncio.create_task(self._watch_device(device_id))
        self._watch_tasks[device_id] = task

    async def remove_device_watcher(self, device_id: str) -> None:
        task = self._watch_tasks.pop(device_id, None)
        if task is not None:
            task.cancel()
            try:
                await task
            except (asyncio.CancelledError, Exception):
                pass
        drv = self._drivers.pop(device_id, None)
        if drv is not None:
            try:
                await drv.disconnect()
            except Exception:
                pass

    async def execute_command(self, device_id: str, state: dict[str, Any]) -> None:
        """Apply a state update to a device through its driver. Used by
        the routes for /devices/{id}/command and /devices/{id}/test.

        Refuses to operate on disabled devices — those are intentionally
        offline (typically tuya_cloud entries where local control isn't
        available). The user must explicitly enable them first.
        """
        async with self._db_session() as session:
            from core.registry.models import Device
            d = await session.get(Device, device_id)
            if d is None:
                raise DriverError(f"Device {device_id} not found in registry")
            if not bool(d.enabled):
                raise DriverError(
                    "Device is disabled — local control unavailable. "
                    "Enable it via PATCH /devices/{id} {\"enabled\": true} "
                    "if you accept cloud-only control."
                )

        # First attempt against the (possibly cached) driver. On any
        # DriverError, drop the cached instance and try once more with a
        # fresh connection. This recovers from session-key desync without
        # waiting for the watcher's exponential backoff.
        drv: DeviceDriver | None = None
        try:
            drv = await self._get_or_create_driver(device_id)
            await drv.set_state(state)
        except DriverError:
            stale = self._drivers.pop(device_id, None)
            if stale is not None:
                try:
                    await stale.disconnect()
                except Exception:
                    pass
            drv = await self._get_or_create_driver(device_id)
            await drv.set_state(state)

        await self.patch_device_state(device_id, state)
        await self.publish("device.state_changed", {
            "device_id": device_id,
            "new_state": state,
            "source": self.name,
        })

    # ── Voice intent handler ─────────────────────────────────────────────

    async def _on_voice_intent(self, event: Any) -> None:
        try:
            payload = event.payload or {}
            intent = payload.get("intent", "")
            if intent not in OWNED_INTENTS:
                return
            params = payload.get("params") or {}

            # Build the target logical state for this intent. Climate intents
            # need parameter parsing; on/off are trivial.
            try:
                target_state = self._intent_to_state(intent, params)
            except ValueError as exc:
                logger.info("device-control: bad params for %s: %s", intent, exc)
                return
            if target_state is None:
                return

            entity_filter = INTENT_ENTITY_FILTER.get(intent)
            device = await self._resolve_device(params, entity_filter=entity_filter)
            if device is None:
                logger.info(
                    "device-control: no device matches intent=%s params=%s",
                    intent, params,
                )
                await self.speak_action(intent, {
                    "result": "not_found",
                    "entity": params.get("entity"),
                    "location": params.get("location"),
                })
                return

            try:
                drv = await self._get_or_create_driver(device["device_id"])
                await drv.set_state(target_state)
            except DriverError as exc:
                logger.warning(
                    "device-control: driver error for %s: %s",
                    device["device_id"], exc,
                )
                await self.speak_action(intent, {
                    "result": "driver_error",
                    "device_name": device["name"],
                    "error": str(exc),
                })
                return

            # Optimistically merge target into stored state.
            current = device.get("state") or {}
            current.update(target_state)
            await self.patch_device_state(device["device_id"], current)
            await self.publish("device.state_changed", {
                "device_id": device["device_id"],
                "new_state": current,
                "source": self.name,
            })

            ack: dict[str, Any] = {
                "result": "ok",
                "device_name": device["name"],
                "location": device.get("location"),
            }
            if intent in (INTENT_ON, INTENT_OFF):
                ack["state"] = "on" if intent == INTENT_ON else "off"
            elif intent == INTENT_SET_TEMPERATURE:
                ack["temperature"] = target_state.get("target_temp")
            elif intent == INTENT_SET_MODE:
                ack["mode"] = target_state.get("mode")
            elif intent == INTENT_SET_FAN_SPEED:
                ack["fan_speed"] = target_state.get("fan_speed")
            await self.speak_action(intent, ack)
        except Exception as exc:
            logger.exception("device-control: voice intent handler crashed: %s", exc)

    # ── Intent → state translation ───────────────────────────────────────

    @staticmethod
    def _intent_to_state(intent: str, params: dict) -> dict[str, Any] | None:
        """Convert ``(intent, params)`` from the voice layer into a logical
        state dict ready for ``driver.set_state()``.

        Returns ``None`` if the intent is not understood (caller bails out
        silently). Raises ``ValueError`` if the intent IS understood but its
        params are missing/invalid (caller logs and bails).
        """
        if intent == INTENT_ON:
            return {"on": True}
        if intent == INTENT_OFF:
            return {"on": False}

        if intent == INTENT_SET_TEMPERATURE:
            raw = params.get("level") or params.get("temperature")
            if raw is None:
                raise ValueError("missing 'level' parameter")
            try:
                level = int(raw)
            except (TypeError, ValueError) as exc:
                raise ValueError(f"non-integer level: {raw!r}") from exc
            return {"target_temp": level}

        if intent == INTENT_SET_MODE:
            raw = (params.get("mode") or "").strip().lower()
            allowed = {"auto", "cool", "dry", "fan", "heat"}
            if raw not in allowed:
                raise ValueError(f"unknown mode: {raw!r}")
            return {"mode": raw}

        if intent == INTENT_SET_FAN_SPEED:
            raw = (params.get("level") or params.get("speed") or "").strip().lower()
            allowed = {
                "auto", "low", "medium_low", "medium", "medium_high", "high",
            }
            # Normalise common spoken aliases.
            aliases = {
                "min": "low",
                "minimum": "low",
                "max": "high",
                "maximum": "high",
                "mid": "medium",
                "middle": "medium",
            }
            raw = aliases.get(raw, raw)
            if raw not in allowed:
                raise ValueError(f"unknown fan speed: {raw!r}")
            return {"fan_speed": raw}

        return None

    # ── Device resolution ────────────────────────────────────────────────

    async def _resolve_device(
        self,
        params: dict,
        entity_filter: tuple[str, ...] | None = None,
    ) -> dict | None:
        """Find ONE device matching params (entity, location, name).

        ``entity_filter`` narrows the candidate set to devices whose
        ``entity_type`` is in the given tuple — used by climate intents so
        a "set temperature" command cannot accidentally match a light or
        switch in the same room.

        Strategy (stops at the first tier that returns exactly one match):
          1. Strict: entity_type AND location both match.
          2. Location-only: only ``location`` supplied or entity missed.
             Matches device.location OR device.name OR meta.name_en —
             the user may say the ROOM, the DISPLAY NAME, or the ENGLISH
             name interchangeably ("turn on the cabinet light" → both
             name and location can be the same word).
          3. Entity-only: only ``entity`` supplied.
          4. Fallback: single-device installation — return it if there's
             exactly one device under our management.

        Returns the device as a dict, or None if zero/many matches.
        """
        from core.registry.models import Device
        from sqlalchemy import or_

        entity = (params.get("entity") or "").lower().strip() or None
        location = (params.get("location") or "").lower().strip() or None

        def _row_to_dict(d) -> dict:
            return {
                "device_id": d.device_id,
                "name": d.name,
                "entity_type": d.entity_type,
                "location": d.location,
                "protocol": d.protocol,
                "state": json.loads(d.state) if d.state else {},
                "meta": json.loads(d.meta) if d.meta else {},
            }

        async with self._db_session() as session:
            base = select(Device).where(
                Device.module_id == self.name,
                Device.enabled == True,  # noqa: E712
            )
            if entity_filter:
                base = base.where(Device.entity_type.in_(entity_filter))

            # Tier 1: both entity_type AND location.
            if entity and location:
                stmt = base.where(
                    Device.entity_type.ilike(f"%{entity}%"),
                    or_(
                        Device.location.ilike(f"%{location}%"),
                        Device.name.ilike(f"%{location}%"),
                        Device.meta.ilike(f'%"name_en": "%{location}%'),
                    ),
                )
                rows = list((await session.execute(stmt)).scalars())
                if len(rows) == 1:
                    return _row_to_dict(rows[0])

            # Tier 2: location-like keyword → search location/name/name_en.
            if location:
                stmt = base.where(
                    or_(
                        Device.location.ilike(f"%{location}%"),
                        Device.name.ilike(f"%{location}%"),
                        Device.meta.ilike(f'%"name_en": "%{location}%'),
                    ),
                )
                rows = list((await session.execute(stmt)).scalars())
                if len(rows) == 1:
                    return _row_to_dict(rows[0])
                # User explicitly specified a location but nothing matched —
                # do NOT fall through to entity-only / single-device fallback,
                # otherwise we'd silently switch rooms (e.g. "kitchen light"
                # turning off the office light). Return None so the caller
                # speaks a "not found" error for the requested location.
                return None

            # Tier 3: entity-type alone.
            if entity:
                stmt = base.where(Device.entity_type.ilike(f"%{entity}%"))
                rows = list((await session.execute(stmt)).scalars())
                if len(rows) == 1:
                    return _row_to_dict(rows[0])

            # Tier 4: single-device install — unambiguous fallback.
            rows = list((await session.execute(base)).scalars())
            if len(rows) == 1:
                return _row_to_dict(rows[0])

        return None

    # ── Watcher loop ─────────────────────────────────────────────────────

    async def _spawn_watchers_for_existing_devices(self) -> None:
        async with self._db_session() as session:
            from core.registry.models import Device
            result = await session.execute(
                select(Device.device_id).where(
                    Device.module_id == self.name,
                    Device.enabled == True,  # noqa: E712
                )
            )
            ids = [r[0] for r in result.all()]
        for did in ids:
            await self.add_device_watcher(did)

    async def _get_or_create_driver(self, device_id: str) -> DeviceDriver:
        if device_id in self._drivers:
            return self._drivers[device_id]
        async with self._db_session() as session:
            from core.registry.models import Device
            d = await session.get(Device, device_id)
            if d is None:
                raise DriverError(f"Device {device_id} not found in registry")
            protocol = d.protocol
            meta = json.loads(d.meta) if d.meta else {}
        drv = get_driver(device_id, protocol, meta)
        self._drivers[device_id] = drv
        return drv

    async def _watch_device(self, device_id: str) -> None:
        """Persistent push watcher with exponential reconnect backoff."""
        attempt = 0
        was_online: bool | None = None
        while not self._stopping:
            try:
                drv = await self._get_or_create_driver(device_id)
                state = await drv.connect()
                attempt = 0
                # Some drivers (e.g. Gree) learn a per-device key during
                # connect() and mutate self.meta in place. Persist that
                # back to the DB so the next reconnect skips the binding
                # handshake.
                await self._persist_driver_meta(device_id, drv)
                if state:
                    await self._apply_external_state(device_id, state)
                await self._publish_metering(device_id, drv)
                if was_online is not True:
                    await self._publish_online(device_id, True)
                    was_online = True

                async for new_state in drv.stream_events():
                    if self._stopping:
                        break
                    if new_state:
                        await self._apply_external_state(device_id, new_state)
                    await self._publish_metering(device_id, drv)
            except asyncio.CancelledError:
                raise
            except DriverError as exc:
                logger.info(
                    "device-control: %s offline (%s) — backing off",
                    device_id, exc,
                )
                if was_online is not False:
                    await self._publish_online(device_id, False)
                    was_online = False
                # Drop the broken driver instance so reconnect builds a fresh one.
                self._drivers.pop(device_id, None)
                attempt += 1

                # No automatic downgrade to cloud — local control is the
                # whole point. The device just stays "offline" until LAN
                # comes back. The user can manually flip enabled=true on a
                # cloud-only device if they accept the internet dependency.
                delay = min(60, 2 ** min(attempt, 6))
                try:
                    await asyncio.sleep(delay)
                except asyncio.CancelledError:
                    raise
            except Exception as exc:
                logger.exception(
                    "device-control: unexpected error in watcher %s: %s",
                    device_id, exc,
                )
                self._drivers.pop(device_id, None)
                try:
                    await asyncio.sleep(15)
                except asyncio.CancelledError:
                    raise

    async def _apply_external_state(self, device_id: str, state: dict) -> None:
        """Persist a state update from the device and broadcast on EventBus."""
        try:
            await self.patch_device_state(device_id, state)
        except Exception:
            pass
        await self.publish("device.state_changed", {
            "device_id": device_id,
            "new_state": state,
            "source": self.name,
        })

    async def _publish_online(self, device_id: str, online: bool) -> None:
        await self.publish(
            "device.online" if online else "device.offline",
            {"device_id": device_id},
        )

    async def _persist_driver_meta(self, device_id: str, drv: Any) -> None:
        """Write back any in-place mutations the driver made to its meta dict.

        Drivers that learn credentials during ``connect()`` (e.g. Gree's
        per-device AES key) update ``drv.meta`` directly. This helper
        diff-checks against the persisted JSON and only writes when the
        contents actually changed, so we don't pound the DB with no-op
        UPDATEs on every reconnect.
        """
        new_meta = getattr(drv, "meta", None)
        if not isinstance(new_meta, dict):
            return
        try:
            new_json = json.dumps(new_meta, sort_keys=True)
        except (TypeError, ValueError):
            return
        try:
            from core.registry.models import Device
            async with self._db_session() as session:
                async with session.begin():
                    d = await session.get(Device, device_id)
                    if d is None:
                        return
                    current_json = json.dumps(
                        json.loads(d.meta) if d.meta else {},
                        sort_keys=True,
                    )
                    if current_json == new_json:
                        return
                    d.set_meta(new_meta)
        except Exception as exc:
            logger.warning(
                "device-control: failed to persist meta for %s: %s",
                device_id, exc,
            )

    async def _publish_metering(self, device_id: str, drv: Any) -> None:
        """Drain any pending power-meter snapshot from the driver and emit
        ``device.power_reading`` on the bus. No-op for drivers that don't
        implement metering."""
        try:
            metering = drv.consume_metering()
        except Exception:
            return
        if not metering or "watts" not in metering:
            return
        await self.publish("device.power_reading", {
            "device_id": device_id,
            "watts": metering["watts"],
            "volts": metering.get("volts"),
            "amps": metering.get("amps"),
            "ts": time.time(),
            "source": self.name,
        })

    # ── Intent ownership claim ────────────────────────────────────────────

    async def _claim_intent_ownership(self) -> None:
        """Set ``module='device-control'`` on every intent we own."""
        if self._session_factory is None:
            return
        async with self._session_factory() as session:
            from core.registry.models import IntentDefinition
            await session.execute(
                update(IntentDefinition)
                .where(IntentDefinition.intent.in_(OWNED_INTENTS))
                .values(module=self.name)
            )
            await session.commit()
