"""Central config for the i18n auto-generation pipeline.

Edit here (not in the generator) to add/remove languages or retune plural
handling. Generator, diff tool, and LanguagePicker component all read from
this single source of truth.
"""

from __future__ import annotations

# Languages where a human maintains `src/i18n/locales/{code}.ts` directly.
# These are first-tier: always loaded, always highest priority, never
# overwritten by the generator.
MANUAL_LANGUAGES: tuple[str, ...] = ("en", "uk")

# Languages generated by Argos Translate on CI. Each code here must exist
# as a usable translation pair from English in the installed Argos package
# set. `ar` (Arabic) is intentionally absent — RTL support deferred to v0.4.1.
AUTO_LANGUAGES: tuple[str, ...] = (
    # Slavic
    "ru",  # Русский
    "pl",  # Polski
    "cs",  # Čeština
    # Germanic
    "de",  # Deutsch
    "nl",  # Nederlands
    # Romance
    "es",  # Español
    "fr",  # Français
    "it",  # Italiano
    "pt",  # Português
    # Turkic
    "tr",  # Türkçe
    # CJK
    "ja",  # 日本語
    "zh",  # 中文
    "ko",  # 한국어
    # South Asia
    "hi",  # हिन्दी
)

# Display metadata for LanguagePicker / Wizard. Keys are the language code,
# values are the NATIVE name (per "native-only" UX decision in the plan).
NATIVE_NAMES: dict[str, str] = {
    "en": "English",
    "uk": "Українська",
    "ru": "Русский",
    "pl": "Polski",
    "cs": "Čeština",
    "de": "Deutsch",
    "nl": "Nederlands",
    "es": "Español",
    "fr": "Français",
    "it": "Italiano",
    "pt": "Português",
    "tr": "Türkçe",
    "ja": "日本語",
    "zh": "中文",
    "ko": "한국어",
    "hi": "हिन्दी",
}

# Text direction per language (for future RTL work).
DIRECTION: dict[str, str] = {code: "ltr" for code in MANUAL_LANGUAGES + AUTO_LANGUAGES}
# DIRECTION["ar"] = "rtl"  # when Arabic lands in v0.4.1

ALL_LANGUAGES: tuple[str, ...] = MANUAL_LANGUAGES + AUTO_LANGUAGES


def quality_tier(code: str) -> str:
    """Return 'manual' for first-tier languages, 'auto' for generated ones."""
    if code in MANUAL_LANGUAGES:
        return "manual"
    if code in AUTO_LANGUAGES:
        return "auto"
    return "unknown"
