#!/bin/bash
# scripts/start-display.sh — Host-side display launcher for SelenaCore
#
# Runs on the HOST (not inside Docker).
# Detects display mode and launches the appropriate UI:
#   desktop     — existing DE session (GNOME/KDE/XFCE) — Chromium kiosk via X11/Wayland
#   kiosk       — cage + cog (WPE WebKit) or Chromium in kiosk mode (Wayland, no DE needed)
#   tty         — Python TUI with QR code + split-panel status on TTY1
#
# Called by selena-display.service (generated by scripts/install-systemd.sh)
# or by ~/.config/autostart after Docker is up.

set -euo pipefail

UI_URL="${SELENA_UI_URL:-http://localhost}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
COMPOSE_FILE="${COMPOSE_FILE:-${SCRIPT_DIR}/../docker-compose.yml}"
LOG="${SELENA_LOG_DIR:-/var/log/selena}/display.log"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG"; }

# ── Wait for core container ─────────────────────────────────────────────
wait_for_core() {
    log "Waiting for core container..."
    for i in $(seq 1 30); do
        docker compose -f "$COMPOSE_FILE" ps core 2>/dev/null | grep -qE "running|healthy" && return 0
        log "waiting... ($i)"
        sleep 3
    done
    log "ERROR: core container not ready after 90s"
    return 1
}

# ── Wait for UI HTTP ─────────────────────────────────────────────────────
wait_for_ui() {
    log "Waiting for UI at $UI_URL ..."
    for i in $(seq 1 30); do
        if curl -sf -o /dev/null "$UI_URL" 2>/dev/null; then
            log "UI is up."
            return 0
        fi
        sleep 2
    done
    log "WARNING: UI not reachable after 60s, proceeding anyway"
}

# ── Find chromium binary ─────────────────────────────────────────────────
find_chromium() {
    command -v chromium 2>/dev/null \
        || command -v chromium-browser 2>/dev/null \
        || { log "ERROR: chromium not found"; return 1; }
}

# ── Find kiosk browser (prefer cog over chromium) ───────────────────────
find_kiosk_browser() {
    # Manual override via env
    if [[ -n "${SELENA_KIOSK_BROWSER:-}" ]]; then
        if command -v "$SELENA_KIOSK_BROWSER" >/dev/null 2>&1; then
            echo "$SELENA_KIOSK_BROWSER"
            return
        fi
        log "WARNING: SELENA_KIOSK_BROWSER=$SELENA_KIOSK_BROWSER not found, auto-detecting"
    fi
    # Prefer cog (WPE WebKit, ~50 MB) over Chromium (~300 MB)
    if command -v cog >/dev/null 2>&1; then
        echo "cog"
        return
    fi
    find_chromium
}

# ── Display mode detection ───────────────────────────────────────────────
detect_mode() {
    # 1. Existing DE session (X11 or Wayland) — use it directly
    if [[ -n "${DISPLAY:-}" ]] || [[ -n "${WAYLAND_DISPLAY:-}" ]]; then
        echo "desktop"
        return
    fi

    # 2. No DE — try cage (Wayland compositor, no DE needed)
    if command -v cage >/dev/null 2>&1 && find_kiosk_browser >/dev/null 2>&1; then
        if ls /dev/dri/card* >/dev/null 2>&1; then
            echo "kiosk"
            return
        fi
    fi

    # Check for framebuffer
    if [[ -e /dev/fb0 ]]; then
        if command -v cage >/dev/null 2>&1 && find_kiosk_browser >/dev/null 2>&1; then
            echo "kiosk"
            return
        fi
    fi

    # 3. Fallback — TTY Python TUI
    echo "tty"
}

# ── Launch ───────────────────────────────────────────────────────────────
main() {
    mkdir -p "$(dirname "$LOG")"
    log "SelenaCore display launcher starting..."

    # Ensure XDG_RUNTIME_DIR exists
    export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
    if [[ ! -d "$XDG_RUNTIME_DIR" ]]; then
        mkdir -p "$XDG_RUNTIME_DIR"
        chmod 0700 "$XDG_RUNTIME_DIR"
        log "Created XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR"
    fi

    wait_for_core || true

    local mode
    mode="$(detect_mode)"
    log "Detected display mode: $mode"

    local KIOSK_URL="${UI_URL}?kiosk=1"

    case "$mode" in
        desktop)
            wait_for_ui

            local CHROMIUM_BIN
            CHROMIUM_BIN="$(find_chromium)"
            log "Launching kiosk via desktop session ($CHROMIUM_BIN) → $UI_URL"

            # Give the DE session time to fully initialize
            sleep 5

            # Cleanup stale X11 sockets from previous runs
            rm -f /tmp/.X11-unix/X1 /tmp/.X11-unix/X2 2>/dev/null || true

            # Hide cursor after 3s of inactivity (moves it off-screen)
            if command -v unclutter >/dev/null 2>&1; then
                unclutter -idle 3 -root &
                log "unclutter started (cursor hides after 3s idle)"
            fi

            local -a CHROMIUM_FLAGS=(
                --kiosk
                --no-sandbox
                --noerrdialogs
                --disable-infobars
                --disable-session-crashed-bubble
                --disable-translate
                --no-first-run
                --disable-features=Translate,TranslateUI,ChromeTranslatePopup
                --check-for-update-interval=31536000
                --autoplay-policy=no-user-gesture-required
                --disable-pinch
                --overscroll-history-navigation=0
                --no-default-browser-check
                --disable-component-update
                --disable-background-networking
                --disable-sync
                --start-fullscreen
                --user-data-dir=/tmp/chromium-kiosk
                --lang=ru
                --disable-popup-blocking
                --disable-prompt-on-repost
                --disable-hang-monitor
                --disable-gpu-sandbox
                --ignore-gpu-blocklist
                --enable-gpu-rasterization
            )

            # Restart loop — keep kiosk alive if Chromium crashes
            while true; do
                log "Starting Chromium kiosk..."
                "$CHROMIUM_BIN" "${CHROMIUM_FLAGS[@]}" "$KIOSK_URL" || true
                log "Chromium exited, restarting in 3s..."
                sleep 3
            done
            ;;

        kiosk)
            wait_for_ui

            local KIOSK_BROWSER
            KIOSK_BROWSER="$(find_kiosk_browser)"
            log "Launching kiosk: cage + $KIOSK_BROWSER → $UI_URL"

            # DRM for display output, libinput for touch/keyboard/mouse
            export WLR_BACKENDS="${WLR_BACKENDS:-drm,libinput}"
            export LIBSEAT_BACKEND="${LIBSEAT_BACKEND:-seatd}"
            export WLR_NO_HARDWARE_CURSORS="${WLR_NO_HARDWARE_CURSORS:-1}"
            export XCURSOR_PATH="${SCRIPT_DIR}/cursors:/usr/share/icons"
            export XCURSOR_THEME=default
            export XCURSOR_SIZE=24

            if [[ "$KIOSK_BROWSER" == "cog" ]]; then
                # cog: single-window WPE WebKit browser, ~50 MB RAM
                # Fullscreen kiosk is the default — no flags needed
                exec cage -s -- cog "$KIOSK_URL"
            else
                # Chromium fallback: requires extensive kiosk flags
                local CHROMIUM_BIN
                CHROMIUM_BIN="$(find_chromium)"
                local -a CHROMIUM_FLAGS=(
                    --kiosk
                    --no-sandbox
                    --noerrdialogs
                    --disable-infobars
                    --disable-session-crashed-bubble
                    --disable-translate
                    --no-first-run
                    --disable-features=Translate,TranslateUI,ChromeTranslatePopup
                    --check-for-update-interval=31536000
                    --autoplay-policy=no-user-gesture-required
                    --disable-pinch
                    --overscroll-history-navigation=0
                    --no-default-browser-check
                    --disable-component-update
                    --disable-background-networking
                    --disable-sync
                    --ozone-platform=wayland
                    --enable-features=OverlayScrollbar
                    --hide-scrollbars
                    --start-fullscreen
                    --user-data-dir=/tmp/chromium-kiosk
                    --disable-gpu-sandbox
                    --lang=ru
                    --disable-popup-blocking
                    --disable-prompt-on-repost
                    --disable-hang-monitor
                )
                exec cage -s -- "$CHROMIUM_BIN" "${CHROMIUM_FLAGS[@]}" "$KIOSK_URL"
            fi
            ;;

        tty|*)
            log "Launching TTY status / QR wizard screen on tty1..."
            local HOST_IP
            HOST_IP=$(hostname -I | awk '{print $1}')
            exec docker compose -f "$COMPOSE_FILE" \
                exec -T -e HOST_IP="$HOST_IP" core \
                python -m system_modules.ui_core.tty_status
            ;;
    esac
}

main "$@"
