[Service]
ExecStartPre=-/bin/bash -c 'mkdir -p /run/user/1000 && chown dotradepro:dotradepro /run/user/1000 && chmod 700 /run/user/1000'
ExecStart=
ExecStart=-/sbin/agetty --autologin dotradepro --noclear %I $TERM
